// generated by scripts/sync-deployments.mjs — do not edit
import type { Address } from 'viem'

export type Deployment = {
  proofOfContribution?: Address
  startBlock?: number
  resourceRegistry?: Address
  resourceRegistryStartBlock?: number
  payeeVaultFactory?: Address
}

export const deployments: Readonly<Record<number, Deployment>> = {
  8453: {
    proofOfContribution: '0xC398F2Fa964245d765C445b87B427e52467225e2',
    startBlock: 51633710,
    resourceRegistry: '0xb80B0b88c55Af8f7Be65c407ae05B15466218d30',
    resourceRegistryStartBlock: 52243308,
    payeeVaultFactory: '0xE01E989dc82547144aE92918104a90336220d0df',
  },
  84532: {
    resourceRegistry: '0xb80B0b88c55Af8f7Be65c407ae05B15466218d30',
    resourceRegistryStartBlock: 47743342,
    payeeVaultFactory: '0xE01E989dc82547144aE92918104a90336220d0df',
  },
}
